name: Build and Test

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: 3.11
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Check code formatting
      run: |
        pip install black
        black --check .
    
    - name: Check file structure
      run: |
        test -f stock_names.json
        test -f working1.py
        test -f Dockerfile
        test -f requirements.txt
    
    - name: Test imports
      run: |
        python -c "import streamlit, yfinance, pandas, numpy; print('All imports successful')"

  docker:
    runs-on: ubuntu-latest
    needs: test
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Build Docker image
      run: |
        docker build -t tradingview-pro .
    
    - name: Test Docker container
      run: |
        docker run --rm -d -p 8501:8501 --name test-app tradingview-pro
        sleep 30
        curl --fail http://localhost:8501/_stcore/health || exit 1
        docker stop test-app
